"""MCP server exposing Bookshelf's (Readarr fork) v1 REST API (OpenAPI 3.0.1) as tools.

Full coverage of every JSON-producing endpoint under /api/v1 plus GET /ping
(binary/text endpoints - media covers and raw log files - are excluded), but
exposed as ~15 resource-scoped *portmanteau* tools instead of one tool per
endpoint. Each portmanteau tool (e.g. bookshelf_queue, bookshelf_media_library)
takes an `operation` enum plus an `arguments` dict; see AGENTS.md for the
rationale (a 200+-tool server blows the MCP context budget on session start).

The vendored spec at tests/data/bookshelf_openapi.json (bookshelf develop)
still generates one async function per endpoint into `_TOOL_REGISTRY` via
scripts/generate_registry.py - keep it in sync with the spec (see AGENTS.md).
Those functions are no longer registered as individual MCP tools; `_GROUPS`
below buckets them by resource, and `_register_group` wraps each bucket in a
single dispatching tool that calls the right function by name. Nothing about
the endpoint functions themselves changes - grouping is purely a
registration-time concern.

Auth is the X-Api-Key header, generated in Bookshelf > Settings > General >
Security. A group tool is marked readOnlyHint=True only when every operation
in it is a GET; mixed groups carry no hints (writes still get a `WRITE:` /
`DESTRUCTIVE:` note in their operation's doc line). Bodies are passed as
opaque dicts/lists. build_client points at the origin with no path suffix so
httpx joins the fully-qualified paths (including /ping) correctly.
"""

import inspect
import os
import sys
from typing import Any, Literal
from urllib.parse import quote

import httpx
from fastmcp import FastMCP
from fastmcp.exceptions import ToolError
from fastmcp.tools import Tool
from mcp.types import ToolAnnotations

READONLY = ToolAnnotations(readOnlyHint=True)
WRITE = ToolAnnotations(readOnlyHint=False, destructiveHint=False)
DESTRUCTIVE = ToolAnnotations(readOnlyHint=False, destructiveHint=True)

# Bookshelf responses are plain JSON. `dict[str, Any]` (not bare `Any`) matters
# here: FastMCP needs a concrete schema to build MCP structured content, and
# skips that step entirely for an `Any` return type -- which silently makes
# Client.call_tool's `.data` come back None for any tool returning a JSON array.
JSONObj = dict[str, Any]
JSONVal = JSONObj | list[Any]

mcp = FastMCP("bookshelf-mcp")

_client: httpx.AsyncClient | None = None


def build_client(
    base_url: str, api_key: str | None, transport: httpx.BaseTransport | None = None
) -> httpx.AsyncClient:
    """Client pinned to the origin (no path suffix) so registered full paths
    like /api/v1/author and /ping both resolve correctly via httpx base join."""
    headers = {"X-Api-Key": api_key} if api_key else {}
    return httpx.AsyncClient(base_url=f"{base_url.rstrip('/')}", headers=headers, transport=transport)


async def _req(
    method: str,
    path: str,
    params: dict[str, Any] | None = None,
    json_body: JSONVal | None = None,
) -> JSONVal:
    assert _client is not None, "client not configured"
    r = await _client.request(method, path, params=params, json=json_body)
    if r.status_code >= 400:
        try:
            msg = r.json().get("message", r.text)
        except ValueError:
            msg = r.text
        raise ToolError(f"Bookshelf API {r.status_code}: {msg}")
    if not r.text:
        return {}
    return r.json()


def _omit(params: dict[str, Any]) -> dict[str, Any]:
    """Drop keys whose values are empty/None so the API's defaults apply."""
    return {k: v for k, v in params.items() if v not in ("", None)}


# Resource groups for portmanteau registration. Every _TOOL_REGISTRY name
# must appear in exactly one group - see test_all_registry_names_grouped.
_GROUPS: dict[str, tuple[str, ...]] = {
    "bookshelf_profiles_formats": (
        'bookshelf_create_customfilter',
        'bookshelf_create_customformat',
        'bookshelf_create_delayprofile',
        'bookshelf_create_metadataprofile',
        'bookshelf_create_qualityprofile',
        'bookshelf_create_releaseprofile',
        'bookshelf_delete_customfilter',
        'bookshelf_delete_customformat',
        'bookshelf_delete_delayprofile',
        'bookshelf_delete_metadataprofile',
        'bookshelf_delete_qualityprofile',
        'bookshelf_delete_releaseprofile',
        'bookshelf_get_customfilter',
        'bookshelf_get_customformat',
        'bookshelf_get_customformat_schema',
        'bookshelf_get_delayprofile',
        'bookshelf_get_language',
        'bookshelf_get_metadataprofile',
        'bookshelf_get_metadataprofile_schema',
        'bookshelf_get_qualitydefinition',
        'bookshelf_get_qualityprofile',
        'bookshelf_get_qualityprofile_schema',
        'bookshelf_get_releaseprofile',
        'bookshelf_list_customfilter',
        'bookshelf_list_customformat',
        'bookshelf_list_delayprofile',
        'bookshelf_list_language',
        'bookshelf_list_metadataprofile',
        'bookshelf_list_qualitydefinition',
        'bookshelf_list_qualityprofile',
        'bookshelf_list_releaseprofile',
        'bookshelf_reorder_delayprofile',
        'bookshelf_update_customfilter',
        'bookshelf_update_customformat',
        'bookshelf_update_delayprofile',
        'bookshelf_update_metadataprofile',
        'bookshelf_update_quality_definitions',
        'bookshelf_update_qualitydefinition',
        'bookshelf_update_qualityprofile',
        'bookshelf_update_releaseprofile',
    ),
    "bookshelf_media_library": (
        'bookshelf_add_books_to_shelf',
        'bookshelf_bulk_delete_author',
        'bookshelf_bulk_delete_book',
        'bookshelf_bulk_delete_bookfile',
        'bookshelf_bulk_update_author',
        'bookshelf_bulk_update_book',
        'bookshelf_bulk_update_bookfile',
        'bookshelf_commit_manual_import',
        'bookshelf_create_author',
        'bookshelf_create_book',
        'bookshelf_delete_author',
        'bookshelf_delete_book',
        'bookshelf_delete_bookfile',
        'bookshelf_get_author',
        'bookshelf_get_book',
        'bookshelf_get_book_overview',
        'bookshelf_get_bookfile',
        'bookshelf_get_parse',
        'bookshelf_get_rename',
        'bookshelf_get_retag',
        'bookshelf_list_author',
        'bookshelf_list_book',
        'bookshelf_list_bookfile',
        'bookshelf_list_edition',
        'bookshelf_list_manualimport',
        'bookshelf_list_series',
        'bookshelf_lookup_author',
        'bookshelf_lookup_book',
        'bookshelf_search',
        'bookshelf_update_author',
        'bookshelf_update_book',
        'bookshelf_update_bookfile',
        'bookshelf_update_books_monitored',
    ),
    "bookshelf_config": (
        'bookshelf_get_config_development',
        'bookshelf_get_config_development_by_id',
        'bookshelf_get_config_downloadclient',
        'bookshelf_get_config_downloadclient_by_id',
        'bookshelf_get_config_host',
        'bookshelf_get_config_host_by_id',
        'bookshelf_get_config_indexer',
        'bookshelf_get_config_indexer_by_id',
        'bookshelf_get_config_mediamanagement',
        'bookshelf_get_config_mediamanagement_by_id',
        'bookshelf_get_config_metadataprovider',
        'bookshelf_get_config_metadataprovider_by_id',
        'bookshelf_get_config_naming',
        'bookshelf_get_config_naming_by_id',
        'bookshelf_get_config_naming_examples',
        'bookshelf_get_config_ui',
        'bookshelf_get_config_ui_by_id',
        'bookshelf_get_localization',
        'bookshelf_list_update',
        'bookshelf_update_config_development',
        'bookshelf_update_config_downloadclient',
        'bookshelf_update_config_host',
        'bookshelf_update_config_indexer',
        'bookshelf_update_config_mediamanagement',
        'bookshelf_update_config_metadataprovider',
        'bookshelf_update_config_naming',
        'bookshelf_update_config_ui',
    ),
    "bookshelf_system_commands": (
        'bookshelf_delete_command',
        'bookshelf_delete_system_backup',
        'bookshelf_get_command',
        'bookshelf_get_health',
        'bookshelf_get_system_routes',
        'bookshelf_get_system_routes_duplicate',
        'bookshelf_get_system_status',
        'bookshelf_get_system_task',
        'bookshelf_get_system_task_by_id',
        'bookshelf_list_command',
        'bookshelf_list_log',
        'bookshelf_list_log_file',
        'bookshelf_list_log_file_update',
        'bookshelf_list_system_backup',
        'bookshelf_ping',
        'bookshelf_restart',
        'bookshelf_restore_backup',
        'bookshelf_restore_backup_upload',
        'bookshelf_run_command',
        'bookshelf_shutdown',
    ),
    "bookshelf_notifications_metadata": (
        'bookshelf_action_metadata',
        'bookshelf_action_notification',
        'bookshelf_create_metadata',
        'bookshelf_create_notification',
        'bookshelf_delete_metadata',
        'bookshelf_delete_notification',
        'bookshelf_get_metadata',
        'bookshelf_get_metadata_schema',
        'bookshelf_get_notification',
        'bookshelf_get_notification_schema',
        'bookshelf_list_metadata',
        'bookshelf_list_notification',
        'bookshelf_test_all_metadata',
        'bookshelf_test_all_notification',
        'bookshelf_test_metadata',
        'bookshelf_test_notification',
        'bookshelf_update_metadata',
        'bookshelf_update_notification',
    ),
    "bookshelf_download_clients": (
        'bookshelf_action_downloadclient',
        'bookshelf_bulk_delete_downloadclient',
        'bookshelf_bulk_update_downloadclient',
        'bookshelf_create_downloadclient',
        'bookshelf_create_remotepathmapping',
        'bookshelf_delete_downloadclient',
        'bookshelf_delete_remotepathmapping',
        'bookshelf_get_downloadclient',
        'bookshelf_get_downloadclient_schema',
        'bookshelf_get_remotepathmapping',
        'bookshelf_list_downloadclient',
        'bookshelf_list_remotepathmapping',
        'bookshelf_test_all_downloadclient',
        'bookshelf_test_downloadclient',
        'bookshelf_update_downloadclient',
        'bookshelf_update_remotepathmapping',
    ),
    "bookshelf_import_lists": (
        'bookshelf_action_importlist',
        'bookshelf_bulk_delete_importlist',
        'bookshelf_bulk_update_importlist',
        'bookshelf_create_importlist',
        'bookshelf_create_importlistexclusion',
        'bookshelf_delete_importlist',
        'bookshelf_delete_importlistexclusion',
        'bookshelf_get_importlist',
        'bookshelf_get_importlist_schema',
        'bookshelf_get_importlistexclusion',
        'bookshelf_list_importlist',
        'bookshelf_list_importlistexclusion',
        'bookshelf_test_all_importlist',
        'bookshelf_test_importlist',
        'bookshelf_update_importlist',
        'bookshelf_update_importlistexclusion',
    ),
    "bookshelf_indexers": (
        'bookshelf_action_indexer',
        'bookshelf_bulk_delete_indexer',
        'bookshelf_bulk_update_indexer',
        'bookshelf_create_indexer',
        'bookshelf_delete_indexer',
        'bookshelf_get_indexer',
        'bookshelf_get_indexer_schema',
        'bookshelf_list_indexer',
        'bookshelf_test_all_indexer',
        'bookshelf_test_indexer',
        'bookshelf_update_indexer',
    ),
    "bookshelf_storage": (
        'bookshelf_create_rootfolder',
        'bookshelf_delete_rootfolder',
        'bookshelf_get_diskspace',
        'bookshelf_get_rootfolder',
        'bookshelf_list_filesystem',
        'bookshelf_list_filesystem_mediafiles',
        'bookshelf_list_filesystem_type',
        'bookshelf_list_rootfolder',
        'bookshelf_update_rootfolder',
    ),
    "bookshelf_history_blocklist": (
        'bookshelf_bulk_delete_blocklist',
        'bookshelf_delete_blocklist',
        'bookshelf_list_blocklist',
        'bookshelf_list_history',
        'bookshelf_list_history_author',
        'bookshelf_list_history_since',
        'bookshelf_mark_history_failed',
    ),
    "bookshelf_queue": (
        'bookshelf_bulk_delete_queue',
        'bookshelf_delete_queue',
        'bookshelf_get_queue_details',
        'bookshelf_get_queue_status',
        'bookshelf_grab_queue_bulk',
        'bookshelf_grab_queue_item',
        'bookshelf_list_queue',
    ),
    "bookshelf_tags": (
        'bookshelf_create_tag',
        'bookshelf_delete_tag',
        'bookshelf_get_tag',
        'bookshelf_get_tag_detail',
        'bookshelf_list_tag',
        'bookshelf_list_tag_detail',
        'bookshelf_update_tag',
    ),
    "bookshelf_wanted": (
        'bookshelf_get_wanted_cutoff',
        'bookshelf_get_wanted_missing',
        'bookshelf_list_wanted_cutoff',
        'bookshelf_list_wanted_missing',
    ),
    "bookshelf_release_search": (
        'bookshelf_get_indexerflag',
        'bookshelf_list_release',
        'bookshelf_push_release',
        'bookshelf_search_releases',
    ),
    "bookshelf_calendar": (
        'bookshelf_get_calendar',
        'bookshelf_list_calendar',
    ),
}


_TOOL_REGISTRY: list[dict[str, Any]] = [
 {'name': 'bookshelf_list_author',
  'method': 'GET',
  'path': '/api/v1/author',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List author.',
 },
 {'name': 'bookshelf_create_author',
  'method': 'POST',
  'path': '/api/v1/author',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create author. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_author',
  'method': 'PUT',
  'path': '/api/v1/author/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [
          {'name': 'move_files', 'wire': 'moveFiles', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Update author. Query params: moveFiles. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_author',
  'method': 'DELETE',
  'path': '/api/v1/author/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [
          {'name': 'delete_files', 'wire': 'deleteFiles', 'type': 'bool', 'default': False},
          {'name': 'add_import_list_exclusion', 'wire': 'addImportListExclusion', 'type': 'bool', 'default': False},
         ],
  'bk': 'none',
  'doc': 'Delete author. Query params: deleteFiles, addImportListExclusion. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_author',
  'method': 'GET',
  'path': '/api/v1/author/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single author by id.',
 },
 {'name': 'bookshelf_bulk_update_author',
  'method': 'PUT',
  'path': '/api/v1/author/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update author editor. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_bulk_delete_author',
  'method': 'DELETE',
  'path': '/api/v1/author/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete author editor. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_lookup_author',
  'method': 'GET',
  'path': '/api/v1/author/lookup',
  'pp': [],
  'qp': [
          {'name': 'term', 'wire': 'term', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Search the metadata provider for authors by term.',
 },
 {'name': 'bookshelf_list_system_backup',
  'method': 'GET',
  'path': '/api/v1/system/backup',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List system backup.',
 },
 {'name': 'bookshelf_delete_system_backup',
  'method': 'DELETE',
  'path': '/api/v1/system/backup/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete system backup. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_restore_backup',
  'method': 'POST',
  'path': '/api/v1/system/backup/restore/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Create system backup restore. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_restore_backup_upload',
  'method': 'POST',
  'path': '/api/v1/system/backup/restore/upload',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create system backup restore upload. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_blocklist',
  'method': 'GET',
  'path': '/api/v1/blocklist',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': 10},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': None},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List blocklist. Query params: page, pageSize, sortKey, sortDirection.',
 },
 {'name': 'bookshelf_delete_blocklist',
  'method': 'DELETE',
  'path': '/api/v1/blocklist/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete blocklist. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_bulk_delete_blocklist',
  'method': 'DELETE',
  'path': '/api/v1/blocklist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete blocklist bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_list_book',
  'method': 'GET',
  'path': '/api/v1/book',
  'pp': [],
  'qp': [
          {'name': 'author_id', 'wire': 'authorId', 'type': 'int', 'default': None},
          {'name': 'book_ids', 'wire': 'bookIds', 'type': 'list[Any]', 'default': None},
          {'name': 'title_slug', 'wire': 'titleSlug', 'type': 'str', 'default': None},
          {'name': 'include_all_author_books', 'wire': 'includeAllAuthorBooks', 'type': 'bool', 'default': False},
         ],
  'bk': 'none',
  'doc': 'List book. Query params: authorId, bookIds, titleSlug, includeAllAuthorBooks.',
 },
 {'name': 'bookshelf_create_book',
  'method': 'POST',
  'path': '/api/v1/book',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create book. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_book_overview',
  'method': 'GET',
  'path': '/api/v1/book/{id}/overview',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single book overview by id.',
 },
 {'name': 'bookshelf_update_book',
  'method': 'PUT',
  'path': '/api/v1/book/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update book. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_book',
  'method': 'DELETE',
  'path': '/api/v1/book/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [
          {'name': 'delete_files', 'wire': 'deleteFiles', 'type': 'bool', 'default': False},
          {'name': 'add_import_list_exclusion', 'wire': 'addImportListExclusion', 'type': 'bool', 'default': False},
         ],
  'bk': 'none',
  'doc': 'Delete book. Query params: deleteFiles, addImportListExclusion. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_book',
  'method': 'GET',
  'path': '/api/v1/book/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single book by id.',
 },
 {'name': 'bookshelf_update_books_monitored',
  'method': 'PUT',
  'path': '/api/v1/book/monitor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Set the monitored state of books in bulk. Body is a BooksMonitoredResource with bookIds and monitored.',
 },
 {'name': 'bookshelf_bulk_update_book',
  'method': 'PUT',
  'path': '/api/v1/book/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update book editor. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_bulk_delete_book',
  'method': 'DELETE',
  'path': '/api/v1/book/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete book editor. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_list_bookfile',
  'method': 'GET',
  'path': '/api/v1/bookfile',
  'pp': [],
  'qp': [
          {'name': 'author_id', 'wire': 'authorId', 'type': 'int', 'default': None},
          {'name': 'book_file_ids', 'wire': 'bookFileIds', 'type': 'list[Any]', 'default': None},
          {'name': 'book_id', 'wire': 'bookId', 'type': 'list[Any]', 'default': None},
          {'name': 'unmapped', 'wire': 'unmapped', 'type': 'bool', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List bookfile. Query params: authorId, bookFileIds, bookId, unmapped.',
 },
 {'name': 'bookshelf_update_bookfile',
  'method': 'PUT',
  'path': '/api/v1/bookfile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update bookfile. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_bookfile',
  'method': 'DELETE',
  'path': '/api/v1/bookfile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete bookfile. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_bookfile',
  'method': 'GET',
  'path': '/api/v1/bookfile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single bookfile by id.',
 },
 {'name': 'bookshelf_bulk_update_bookfile',
  'method': 'PUT',
  'path': '/api/v1/bookfile/editor',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update bookfile editor. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_bulk_delete_bookfile',
  'method': 'DELETE',
  'path': '/api/v1/bookfile/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete bookfile bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_lookup_book',
  'method': 'GET',
  'path': '/api/v1/book/lookup',
  'pp': [],
  'qp': [
          {'name': 'term', 'wire': 'term', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Search the metadata provider for books by term.',
 },
 {'name': 'bookshelf_add_books_to_shelf',
  'method': 'POST',
  'path': '/api/v1/bookshelf',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add the given books to a Goodreads/Hardcover shelf. Body is a BookshelfResource with bookshelfId and bookIds.',
 },
 {'name': 'bookshelf_list_calendar',
  'method': 'GET',
  'path': '/api/v1/calendar',
  'pp': [],
  'qp': [
          {'name': 'start', 'wire': 'start', 'type': 'str', 'default': None},
          {'name': 'end', 'wire': 'end', 'type': 'str', 'default': None},
          {'name': 'unmonitored', 'wire': 'unmonitored', 'type': 'bool', 'default': False},
          {'name': 'include_author', 'wire': 'includeAuthor', 'type': 'bool', 'default': False},
         ],
  'bk': 'none',
  'doc': 'List calendar. Query params: start, end, unmonitored, includeAuthor.',
 },
 {'name': 'bookshelf_get_calendar',
  'method': 'GET',
  'path': '/api/v1/calendar/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single calendar by id.',
 },
 {'name': 'bookshelf_run_command',
  'method': 'POST',
  'path': '/api/v1/command',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Run a Bookshelf command (body is a CommandResource with a `name`, e.g. RefreshAuthor, AuthorSearch, BookSearch, DownloadedBooksScan, RenamedBookFiles, RescanFolders, MetadataRefresh). WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_command',
  'method': 'GET',
  'path': '/api/v1/command',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List command.',
 },
 {'name': 'bookshelf_delete_command',
  'method': 'DELETE',
  'path': '/api/v1/command/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete command. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_command',
  'method': 'GET',
  'path': '/api/v1/command/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single command by id.',
 },
 {'name': 'bookshelf_list_customfilter',
  'method': 'GET',
  'path': '/api/v1/customfilter',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List customfilter.',
 },
 {'name': 'bookshelf_create_customfilter',
  'method': 'POST',
  'path': '/api/v1/customfilter',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create customfilter. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_customfilter',
  'method': 'PUT',
  'path': '/api/v1/customfilter/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update customfilter. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_customfilter',
  'method': 'DELETE',
  'path': '/api/v1/customfilter/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete customfilter. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_customfilter',
  'method': 'GET',
  'path': '/api/v1/customfilter/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single customfilter by id.',
 },
 {'name': 'bookshelf_create_customformat',
  'method': 'POST',
  'path': '/api/v1/customformat',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create customformat. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_customformat',
  'method': 'GET',
  'path': '/api/v1/customformat',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List customformat.',
 },
 {'name': 'bookshelf_update_customformat',
  'method': 'PUT',
  'path': '/api/v1/customformat/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update customformat. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_customformat',
  'method': 'DELETE',
  'path': '/api/v1/customformat/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete customformat. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_customformat',
  'method': 'GET',
  'path': '/api/v1/customformat/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single customformat by id.',
 },
 {'name': 'bookshelf_get_customformat_schema',
  'method': 'GET',
  'path': '/api/v1/customformat/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List customformat schema.',
 },
 {'name': 'bookshelf_list_wanted_cutoff',
  'method': 'GET',
  'path': '/api/v1/wanted/cutoff',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': 10},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': None},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': None},
          {'name': 'include_author', 'wire': 'includeAuthor', 'type': 'bool', 'default': False},
          {'name': 'monitored', 'wire': 'monitored', 'type': 'bool', 'default': True},
         ],
  'bk': 'none',
  'doc': 'List wanted cutoff. Query params: page, pageSize, sortKey, sortDirection, includeAuthor, monitored.',
 },
 {'name': 'bookshelf_get_wanted_cutoff',
  'method': 'GET',
  'path': '/api/v1/wanted/cutoff/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single wanted cutoff by id.',
 },
 {'name': 'bookshelf_create_delayprofile',
  'method': 'POST',
  'path': '/api/v1/delayprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create delayprofile. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_delayprofile',
  'method': 'GET',
  'path': '/api/v1/delayprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List delayprofile.',
 },
 {'name': 'bookshelf_delete_delayprofile',
  'method': 'DELETE',
  'path': '/api/v1/delayprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete delayprofile. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_update_delayprofile',
  'method': 'PUT',
  'path': '/api/v1/delayprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update delayprofile. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_delayprofile',
  'method': 'GET',
  'path': '/api/v1/delayprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single delayprofile by id.',
 },
 {'name': 'bookshelf_reorder_delayprofile',
  'method': 'PUT',
  'path': '/api/v1/delayprofile/reorder/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [
          {'name': 'after_id', 'wire': 'afterId', 'type': 'int', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Update delayprofile reorder. Query params: afterId. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_development',
  'method': 'GET',
  'path': '/api/v1/config/development',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List config development.',
 },
 {'name': 'bookshelf_update_config_development',
  'method': 'PUT',
  'path': '/api/v1/config/development/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update config development. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_development_by_id',
  'method': 'GET',
  'path': '/api/v1/config/development/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single config development by id.',
 },
 {'name': 'bookshelf_get_diskspace',
  'method': 'GET',
  'path': '/api/v1/diskspace',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List diskspace.',
 },
 {'name': 'bookshelf_list_downloadclient',
  'method': 'GET',
  'path': '/api/v1/downloadclient',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List downloadclient.',
 },
 {'name': 'bookshelf_create_downloadclient',
  'method': 'POST',
  'path': '/api/v1/downloadclient',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create downloadclient. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_downloadclient',
  'method': 'PUT',
  'path': '/api/v1/downloadclient/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Update downloadclient. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_downloadclient',
  'method': 'DELETE',
  'path': '/api/v1/downloadclient/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete downloadclient. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_downloadclient',
  'method': 'GET',
  'path': '/api/v1/downloadclient/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single downloadclient by id.',
 },
 {'name': 'bookshelf_bulk_update_downloadclient',
  'method': 'PUT',
  'path': '/api/v1/downloadclient/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update downloadclient bulk. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_bulk_delete_downloadclient',
  'method': 'DELETE',
  'path': '/api/v1/downloadclient/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete downloadclient bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_downloadclient_schema',
  'method': 'GET',
  'path': '/api/v1/downloadclient/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List downloadclient schema.',
 },
 {'name': 'bookshelf_test_downloadclient',
  'method': 'POST',
  'path': '/api/v1/downloadclient/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create downloadclient test. Query params: forceTest. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_test_all_downloadclient',
  'method': 'POST',
  'path': '/api/v1/downloadclient/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create downloadclient testall. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_action_downloadclient',
  'method': 'POST',
  'path': '/api/v1/downloadclient/action/{name}',
  'pp': [
          {'name': 'name', 'wire': 'name', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create downloadclient action. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_downloadclient',
  'method': 'GET',
  'path': '/api/v1/config/downloadclient',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List config downloadclient.',
 },
 {'name': 'bookshelf_update_config_downloadclient',
  'method': 'PUT',
  'path': '/api/v1/config/downloadclient/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update config downloadclient. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_downloadclient_by_id',
  'method': 'GET',
  'path': '/api/v1/config/downloadclient/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single config downloadclient by id.',
 },
 {'name': 'bookshelf_list_edition',
  'method': 'GET',
  'path': '/api/v1/edition',
  'pp': [],
  'qp': [
          {'name': 'book_id', 'wire': 'bookId', 'type': 'list[Any]', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List edition. Query params: bookId.',
 },
 {'name': 'bookshelf_list_filesystem',
  'method': 'GET',
  'path': '/api/v1/filesystem',
  'pp': [],
  'qp': [
          {'name': 'path', 'wire': 'path', 'type': 'str', 'default': None},
          {'name': 'include_files', 'wire': 'includeFiles', 'type': 'bool', 'default': False},
          {'name': 'allow_folders_without_trailing_slashes', 'wire': 'allowFoldersWithoutTrailingSlashes', 'type': 'bool', 'default': False},
         ],
  'bk': 'none',
  'doc': 'List filesystem. Query params: path, includeFiles, allowFoldersWithoutTrailingSlashes.',
 },
 {'name': 'bookshelf_list_filesystem_type',
  'method': 'GET',
  'path': '/api/v1/filesystem/type',
  'pp': [],
  'qp': [
          {'name': 'path', 'wire': 'path', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List filesystem type. Query params: path.',
 },
 {'name': 'bookshelf_list_filesystem_mediafiles',
  'method': 'GET',
  'path': '/api/v1/filesystem/mediafiles',
  'pp': [],
  'qp': [
          {'name': 'path', 'wire': 'path', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List filesystem mediafiles. Query params: path.',
 },
 {'name': 'bookshelf_get_health',
  'method': 'GET',
  'path': '/api/v1/health',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List health.',
 },
 {'name': 'bookshelf_list_history',
  'method': 'GET',
  'path': '/api/v1/history',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': 10},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': None},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': None},
          {'name': 'include_author', 'wire': 'includeAuthor', 'type': 'bool', 'default': None},
          {'name': 'include_book', 'wire': 'includeBook', 'type': 'bool', 'default': None},
          {'name': 'event_type', 'wire': 'eventType', 'type': 'list[Any]', 'default': None},
          {'name': 'book_id', 'wire': 'bookId', 'type': 'int', 'default': None},
          {'name': 'download_id', 'wire': 'downloadId', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List history. Query params: page, pageSize, sortKey, sortDirection, includeAuthor, includeBook, eventType, bookId, downloadId.',
 },
 {'name': 'bookshelf_list_history_since',
  'method': 'GET',
  'path': '/api/v1/history/since',
  'pp': [],
  'qp': [
          {'name': 'date', 'wire': 'date', 'type': 'str', 'default': None},
          {'name': 'event_type', 'wire': 'eventType', 'type': 'str', 'default': None},
          {'name': 'include_author', 'wire': 'includeAuthor', 'type': 'bool', 'default': False},
          {'name': 'include_book', 'wire': 'includeBook', 'type': 'bool', 'default': False},
         ],
  'bk': 'none',
  'doc': 'List history since. Query params: date, eventType, includeAuthor, includeBook.',
 },
 {'name': 'bookshelf_list_history_author',
  'method': 'GET',
  'path': '/api/v1/history/author',
  'pp': [],
  'qp': [
          {'name': 'author_id', 'wire': 'authorId', 'type': 'int', 'default': None},
          {'name': 'book_id', 'wire': 'bookId', 'type': 'int', 'default': None},
          {'name': 'event_type', 'wire': 'eventType', 'type': 'str', 'default': None},
          {'name': 'include_author', 'wire': 'includeAuthor', 'type': 'bool', 'default': False},
          {'name': 'include_book', 'wire': 'includeBook', 'type': 'bool', 'default': False},
         ],
  'bk': 'none',
  'doc': 'List history author. Query params: authorId, bookId, eventType, includeAuthor, includeBook.',
 },
 {'name': 'bookshelf_mark_history_failed',
  'method': 'POST',
  'path': '/api/v1/history/failed/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Mark a history event as failed and trigger a re-search. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_host',
  'method': 'GET',
  'path': '/api/v1/config/host',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List config host.',
 },
 {'name': 'bookshelf_update_config_host',
  'method': 'PUT',
  'path': '/api/v1/config/host/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update config host. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_host_by_id',
  'method': 'GET',
  'path': '/api/v1/config/host/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single config host by id.',
 },
 {'name': 'bookshelf_list_importlist',
  'method': 'GET',
  'path': '/api/v1/importlist',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List importlist.',
 },
 {'name': 'bookshelf_create_importlist',
  'method': 'POST',
  'path': '/api/v1/importlist',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create importlist. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_importlist',
  'method': 'PUT',
  'path': '/api/v1/importlist/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Update importlist. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_importlist',
  'method': 'DELETE',
  'path': '/api/v1/importlist/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete importlist. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_importlist',
  'method': 'GET',
  'path': '/api/v1/importlist/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single importlist by id.',
 },
 {'name': 'bookshelf_bulk_update_importlist',
  'method': 'PUT',
  'path': '/api/v1/importlist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update importlist bulk. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_bulk_delete_importlist',
  'method': 'DELETE',
  'path': '/api/v1/importlist/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete importlist bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_importlist_schema',
  'method': 'GET',
  'path': '/api/v1/importlist/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List importlist schema.',
 },
 {'name': 'bookshelf_test_importlist',
  'method': 'POST',
  'path': '/api/v1/importlist/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create importlist test. Query params: forceTest. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_test_all_importlist',
  'method': 'POST',
  'path': '/api/v1/importlist/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create importlist testall. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_action_importlist',
  'method': 'POST',
  'path': '/api/v1/importlist/action/{name}',
  'pp': [
          {'name': 'name', 'wire': 'name', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create importlist action. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_importlistexclusion',
  'method': 'GET',
  'path': '/api/v1/importlistexclusion',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List importlistexclusion.',
 },
 {'name': 'bookshelf_create_importlistexclusion',
  'method': 'POST',
  'path': '/api/v1/importlistexclusion',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create importlistexclusion. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_importlistexclusion',
  'method': 'PUT',
  'path': '/api/v1/importlistexclusion/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update importlistexclusion. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_importlistexclusion',
  'method': 'DELETE',
  'path': '/api/v1/importlistexclusion/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete importlistexclusion. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_importlistexclusion',
  'method': 'GET',
  'path': '/api/v1/importlistexclusion/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single importlistexclusion by id.',
 },
 {'name': 'bookshelf_list_indexer',
  'method': 'GET',
  'path': '/api/v1/indexer',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexer.',
 },
 {'name': 'bookshelf_create_indexer',
  'method': 'POST',
  'path': '/api/v1/indexer',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create indexer. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_indexer',
  'method': 'PUT',
  'path': '/api/v1/indexer/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Update indexer. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_indexer',
  'method': 'DELETE',
  'path': '/api/v1/indexer/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete indexer. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_indexer',
  'method': 'GET',
  'path': '/api/v1/indexer/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single indexer by id.',
 },
 {'name': 'bookshelf_bulk_update_indexer',
  'method': 'PUT',
  'path': '/api/v1/indexer/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk update indexer bulk. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_bulk_delete_indexer',
  'method': 'DELETE',
  'path': '/api/v1/indexer/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Bulk delete indexer bulk. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_indexer_schema',
  'method': 'GET',
  'path': '/api/v1/indexer/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexer schema.',
 },
 {'name': 'bookshelf_test_indexer',
  'method': 'POST',
  'path': '/api/v1/indexer/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create indexer test. Query params: forceTest. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_test_all_indexer',
  'method': 'POST',
  'path': '/api/v1/indexer/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create indexer testall. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_action_indexer',
  'method': 'POST',
  'path': '/api/v1/indexer/action/{name}',
  'pp': [
          {'name': 'name', 'wire': 'name', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create indexer action. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_indexer',
  'method': 'GET',
  'path': '/api/v1/config/indexer',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List config indexer.',
 },
 {'name': 'bookshelf_update_config_indexer',
  'method': 'PUT',
  'path': '/api/v1/config/indexer/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update config indexer. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_indexer_by_id',
  'method': 'GET',
  'path': '/api/v1/config/indexer/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single config indexer by id.',
 },
 {'name': 'bookshelf_get_indexerflag',
  'method': 'GET',
  'path': '/api/v1/indexerflag',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List indexerflag.',
 },
 {'name': 'bookshelf_list_language',
  'method': 'GET',
  'path': '/api/v1/language',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List language.',
 },
 {'name': 'bookshelf_get_language',
  'method': 'GET',
  'path': '/api/v1/language/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single language by id.',
 },
 {'name': 'bookshelf_get_localization',
  'method': 'GET',
  'path': '/api/v1/localization',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List localization.',
 },
 {'name': 'bookshelf_list_log',
  'method': 'GET',
  'path': '/api/v1/log',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': 10},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': None},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': None},
          {'name': 'level', 'wire': 'level', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List log. Query params: page, pageSize, sortKey, sortDirection, level.',
 },
 {'name': 'bookshelf_list_log_file',
  'method': 'GET',
  'path': '/api/v1/log/file',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List log file.',
 },
 {'name': 'bookshelf_commit_manual_import',
  'method': 'POST',
  'path': '/api/v1/manualimport',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Commit manual imports for the given files. Body is a list of ManualImportUpdateResource. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_manualimport',
  'method': 'GET',
  'path': '/api/v1/manualimport',
  'pp': [],
  'qp': [
          {'name': 'folder', 'wire': 'folder', 'type': 'str', 'default': None},
          {'name': 'download_id', 'wire': 'downloadId', 'type': 'str', 'default': None},
          {'name': 'author_id', 'wire': 'authorId', 'type': 'int', 'default': None},
          {'name': 'filter_existing_files', 'wire': 'filterExistingFiles', 'type': 'bool', 'default': True},
          {'name': 'replace_existing_files', 'wire': 'replaceExistingFiles', 'type': 'bool', 'default': True},
         ],
  'bk': 'none',
  'doc': 'List manualimport. Query params: folder, downloadId, authorId, filterExistingFiles, replaceExistingFiles.',
 },
 {'name': 'bookshelf_get_config_mediamanagement',
  'method': 'GET',
  'path': '/api/v1/config/mediamanagement',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List config mediamanagement.',
 },
 {'name': 'bookshelf_update_config_mediamanagement',
  'method': 'PUT',
  'path': '/api/v1/config/mediamanagement/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update config mediamanagement. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_mediamanagement_by_id',
  'method': 'GET',
  'path': '/api/v1/config/mediamanagement/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single config mediamanagement by id.',
 },
 {'name': 'bookshelf_list_metadata',
  'method': 'GET',
  'path': '/api/v1/metadata',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List metadata.',
 },
 {'name': 'bookshelf_create_metadata',
  'method': 'POST',
  'path': '/api/v1/metadata',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create metadata. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_metadata',
  'method': 'PUT',
  'path': '/api/v1/metadata/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Update metadata. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_metadata',
  'method': 'DELETE',
  'path': '/api/v1/metadata/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete metadata. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_metadata',
  'method': 'GET',
  'path': '/api/v1/metadata/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single metadata by id.',
 },
 {'name': 'bookshelf_get_metadata_schema',
  'method': 'GET',
  'path': '/api/v1/metadata/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List metadata schema.',
 },
 {'name': 'bookshelf_test_metadata',
  'method': 'POST',
  'path': '/api/v1/metadata/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create metadata test. Query params: forceTest. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_test_all_metadata',
  'method': 'POST',
  'path': '/api/v1/metadata/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create metadata testall. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_action_metadata',
  'method': 'POST',
  'path': '/api/v1/metadata/action/{name}',
  'pp': [
          {'name': 'name', 'wire': 'name', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create metadata action. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_create_metadataprofile',
  'method': 'POST',
  'path': '/api/v1/metadataprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create metadataprofile. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_metadataprofile',
  'method': 'GET',
  'path': '/api/v1/metadataprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List metadataprofile.',
 },
 {'name': 'bookshelf_delete_metadataprofile',
  'method': 'DELETE',
  'path': '/api/v1/metadataprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete metadataprofile. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_update_metadataprofile',
  'method': 'PUT',
  'path': '/api/v1/metadataprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update metadataprofile. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_metadataprofile',
  'method': 'GET',
  'path': '/api/v1/metadataprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single metadataprofile by id.',
 },
 {'name': 'bookshelf_get_metadataprofile_schema',
  'method': 'GET',
  'path': '/api/v1/metadataprofile/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List metadataprofile schema.',
 },
 {'name': 'bookshelf_get_config_metadataprovider',
  'method': 'GET',
  'path': '/api/v1/config/metadataprovider',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List config metadataprovider.',
 },
 {'name': 'bookshelf_update_config_metadataprovider',
  'method': 'PUT',
  'path': '/api/v1/config/metadataprovider/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update config metadataprovider. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_metadataprovider_by_id',
  'method': 'GET',
  'path': '/api/v1/config/metadataprovider/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single config metadataprovider by id.',
 },
 {'name': 'bookshelf_list_wanted_missing',
  'method': 'GET',
  'path': '/api/v1/wanted/missing',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': 10},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': None},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': None},
          {'name': 'include_author', 'wire': 'includeAuthor', 'type': 'bool', 'default': False},
          {'name': 'monitored', 'wire': 'monitored', 'type': 'bool', 'default': True},
         ],
  'bk': 'none',
  'doc': 'List wanted missing. Query params: page, pageSize, sortKey, sortDirection, includeAuthor, monitored.',
 },
 {'name': 'bookshelf_get_wanted_missing',
  'method': 'GET',
  'path': '/api/v1/wanted/missing/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single wanted missing by id.',
 },
 {'name': 'bookshelf_get_config_naming',
  'method': 'GET',
  'path': '/api/v1/config/naming',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List config naming.',
 },
 {'name': 'bookshelf_update_config_naming',
  'method': 'PUT',
  'path': '/api/v1/config/naming/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update config naming. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_naming_by_id',
  'method': 'GET',
  'path': '/api/v1/config/naming/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single config naming by id.',
 },
 {'name': 'bookshelf_get_config_naming_examples',
  'method': 'GET',
  'path': '/api/v1/config/naming/examples',
  'pp': [],
  'qp': [
          {'name': 'rename_books', 'wire': 'renameBooks', 'type': 'bool', 'default': None},
          {'name': 'replace_illegal_characters', 'wire': 'replaceIllegalCharacters', 'type': 'bool', 'default': None},
          {'name': 'colon_replacement_format', 'wire': 'colonReplacementFormat', 'type': 'int', 'default': None},
          {'name': 'standard_book_format', 'wire': 'standardBookFormat', 'type': 'str', 'default': None},
          {'name': 'author_folder_format', 'wire': 'authorFolderFormat', 'type': 'str', 'default': None},
          {'name': 'include_author_name', 'wire': 'includeAuthorName', 'type': 'bool', 'default': None},
          {'name': 'include_book_title', 'wire': 'includeBookTitle', 'type': 'bool', 'default': None},
          {'name': 'include_quality', 'wire': 'includeQuality', 'type': 'bool', 'default': None},
          {'name': 'replace_spaces', 'wire': 'replaceSpaces', 'type': 'bool', 'default': None},
          {'name': 'separator', 'wire': 'separator', 'type': 'str', 'default': None},
          {'name': 'number_style', 'wire': 'numberStyle', 'type': 'str', 'default': None},
          {'name': 'id', 'wire': 'id', 'type': 'int', 'default': None},
          {'name': 'resource_name', 'wire': 'resourceName', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List config naming examples. Query params: renameBooks, replaceIllegalCharacters, colonReplacementFormat, standardBookFormat, authorFolderFormat, includeAuthorName, includeBookTitle, includeQuality, replaceSpaces, separator, numberStyle, id, resourceName.',
 },
 {'name': 'bookshelf_list_notification',
  'method': 'GET',
  'path': '/api/v1/notification',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List notification.',
 },
 {'name': 'bookshelf_create_notification',
  'method': 'POST',
  'path': '/api/v1/notification',
  'pp': [],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create notification. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_notification',
  'method': 'PUT',
  'path': '/api/v1/notification/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [
          {'name': 'force_save', 'wire': 'forceSave', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Update notification. Query params: forceSave. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_notification',
  'method': 'DELETE',
  'path': '/api/v1/notification/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete notification. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_notification',
  'method': 'GET',
  'path': '/api/v1/notification/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single notification by id.',
 },
 {'name': 'bookshelf_get_notification_schema',
  'method': 'GET',
  'path': '/api/v1/notification/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List notification schema.',
 },
 {'name': 'bookshelf_test_notification',
  'method': 'POST',
  'path': '/api/v1/notification/test',
  'pp': [],
  'qp': [
          {'name': 'force_test', 'wire': 'forceTest', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Create notification test. Query params: forceTest. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_test_all_notification',
  'method': 'POST',
  'path': '/api/v1/notification/testall',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create notification testall. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_action_notification',
  'method': 'POST',
  'path': '/api/v1/notification/action/{name}',
  'pp': [
          {'name': 'name', 'wire': 'name', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create notification action. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_parse',
  'method': 'GET',
  'path': '/api/v1/parse',
  'pp': [],
  'qp': [
          {'name': 'title', 'wire': 'title', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Parse a file or release title and show how Bookshelf interprets it.',
 },
 {'name': 'bookshelf_ping',
  'method': 'GET',
  'path': '/ping',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List ping.',
 },
 {'name': 'bookshelf_update_qualitydefinition',
  'method': 'PUT',
  'path': '/api/v1/qualitydefinition/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update qualitydefinition. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_qualitydefinition',
  'method': 'GET',
  'path': '/api/v1/qualitydefinition/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single qualitydefinition by id.',
 },
 {'name': 'bookshelf_list_qualitydefinition',
  'method': 'GET',
  'path': '/api/v1/qualitydefinition',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List qualitydefinition.',
 },
 {'name': 'bookshelf_update_quality_definitions',
  'method': 'PUT',
  'path': '/api/v1/qualitydefinition/update',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Update qualitydefinition update. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_create_qualityprofile',
  'method': 'POST',
  'path': '/api/v1/qualityprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create qualityprofile. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_qualityprofile',
  'method': 'GET',
  'path': '/api/v1/qualityprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List qualityprofile.',
 },
 {'name': 'bookshelf_delete_qualityprofile',
  'method': 'DELETE',
  'path': '/api/v1/qualityprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete qualityprofile. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_update_qualityprofile',
  'method': 'PUT',
  'path': '/api/v1/qualityprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update qualityprofile. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_qualityprofile',
  'method': 'GET',
  'path': '/api/v1/qualityprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single qualityprofile by id.',
 },
 {'name': 'bookshelf_get_qualityprofile_schema',
  'method': 'GET',
  'path': '/api/v1/qualityprofile/schema',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List qualityprofile schema.',
 },
 {'name': 'bookshelf_delete_queue',
  'method': 'DELETE',
  'path': '/api/v1/queue/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [
          {'name': 'remove_from_client', 'wire': 'removeFromClient', 'type': 'bool', 'default': True},
          {'name': 'blocklist', 'wire': 'blocklist', 'type': 'bool', 'default': False},
          {'name': 'skip_redownload', 'wire': 'skipRedownload', 'type': 'bool', 'default': False},
          {'name': 'change_category', 'wire': 'changeCategory', 'type': 'bool', 'default': False},
         ],
  'bk': 'none',
  'doc': 'Delete queue. Query params: removeFromClient, blocklist, skipRedownload, changeCategory. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_bulk_delete_queue',
  'method': 'DELETE',
  'path': '/api/v1/queue/bulk',
  'pp': [],
  'qp': [
          {'name': 'remove_from_client', 'wire': 'removeFromClient', 'type': 'bool', 'default': True},
          {'name': 'blocklist', 'wire': 'blocklist', 'type': 'bool', 'default': False},
          {'name': 'skip_redownload', 'wire': 'skipRedownload', 'type': 'bool', 'default': False},
          {'name': 'change_category', 'wire': 'changeCategory', 'type': 'bool', 'default': False},
         ],
  'bk': 'dict',
  'doc': 'Bulk delete queue bulk. Query params: removeFromClient, blocklist, skipRedownload, changeCategory. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_list_queue',
  'method': 'GET',
  'path': '/api/v1/queue',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'page_size', 'wire': 'pageSize', 'type': 'int', 'default': 10},
          {'name': 'sort_key', 'wire': 'sortKey', 'type': 'str', 'default': None},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': None},
          {'name': 'include_unknown_author_items', 'wire': 'includeUnknownAuthorItems', 'type': 'bool', 'default': False},
          {'name': 'include_author', 'wire': 'includeAuthor', 'type': 'bool', 'default': False},
          {'name': 'include_book', 'wire': 'includeBook', 'type': 'bool', 'default': False},
         ],
  'bk': 'none',
  'doc': 'List queue. Query params: page, pageSize, sortKey, sortDirection, includeUnknownAuthorItems, includeAuthor, includeBook.',
 },
 {'name': 'bookshelf_grab_queue_item',
  'method': 'POST',
  'path': '/api/v1/queue/grab/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Grab a single queue item now.',
 },
 {'name': 'bookshelf_grab_queue_bulk',
  'method': 'POST',
  'path': '/api/v1/queue/grab/bulk',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Grab multiple queue items now. Body is a QueueBulkResource with ids.',
 },
 {'name': 'bookshelf_get_queue_details',
  'method': 'GET',
  'path': '/api/v1/queue/details',
  'pp': [],
  'qp': [
          {'name': 'author_id', 'wire': 'authorId', 'type': 'int', 'default': None},
          {'name': 'book_ids', 'wire': 'bookIds', 'type': 'list[Any]', 'default': None},
          {'name': 'include_author', 'wire': 'includeAuthor', 'type': 'bool', 'default': False},
          {'name': 'include_book', 'wire': 'includeBook', 'type': 'bool', 'default': True},
         ],
  'bk': 'none',
  'doc': 'List detailed queue items for an author or books.',
 },
 {'name': 'bookshelf_get_queue_status',
  'method': 'GET',
  'path': '/api/v1/queue/status',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get queue statistics: total/full count and warnings.',
 },
 {'name': 'bookshelf_search_releases',
  'method': 'POST',
  'path': '/api/v1/release',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Trigger a release search for a book and grab the given release. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_release',
  'method': 'GET',
  'path': '/api/v1/release',
  'pp': [],
  'qp': [
          {'name': 'book_id', 'wire': 'bookId', 'type': 'int', 'default': None},
          {'name': 'author_id', 'wire': 'authorId', 'type': 'int', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List release. Query params: bookId, authorId.',
 },
 {'name': 'bookshelf_list_releaseprofile',
  'method': 'GET',
  'path': '/api/v1/releaseprofile',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List releaseprofile.',
 },
 {'name': 'bookshelf_create_releaseprofile',
  'method': 'POST',
  'path': '/api/v1/releaseprofile',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create releaseprofile. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_releaseprofile',
  'method': 'PUT',
  'path': '/api/v1/releaseprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update releaseprofile. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_releaseprofile',
  'method': 'DELETE',
  'path': '/api/v1/releaseprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete releaseprofile. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_releaseprofile',
  'method': 'GET',
  'path': '/api/v1/releaseprofile/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single releaseprofile by id.',
 },
 {'name': 'bookshelf_push_release',
  'method': 'POST',
  'path': '/api/v1/release/push',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Push a release to Bookshelf (e.g. from an external downloader); body is a ReleaseResource with title and downloadUrl.',
 },
 {'name': 'bookshelf_create_remotepathmapping',
  'method': 'POST',
  'path': '/api/v1/remotepathmapping',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create remotepathmapping. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_remotepathmapping',
  'method': 'GET',
  'path': '/api/v1/remotepathmapping',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List remotepathmapping.',
 },
 {'name': 'bookshelf_delete_remotepathmapping',
  'method': 'DELETE',
  'path': '/api/v1/remotepathmapping/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete remotepathmapping. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_update_remotepathmapping',
  'method': 'PUT',
  'path': '/api/v1/remotepathmapping/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update remotepathmapping. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_remotepathmapping',
  'method': 'GET',
  'path': '/api/v1/remotepathmapping/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single remotepathmapping by id.',
 },
 {'name': 'bookshelf_get_rename',
  'method': 'GET',
  'path': '/api/v1/rename',
  'pp': [],
  'qp': [
          {'name': 'author_id', 'wire': 'authorId', 'type': 'int', 'default': None},
          {'name': 'book_id', 'wire': 'bookId', 'type': 'int', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List proposed renames for an author or book (files that would be renamed on the next rename task).',
 },
 {'name': 'bookshelf_get_retag',
  'method': 'GET',
  'path': '/api/v1/retag',
  'pp': [],
  'qp': [
          {'name': 'author_id', 'wire': 'authorId', 'type': 'int', 'default': None},
          {'name': 'book_id', 'wire': 'bookId', 'type': 'int', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List proposed file retags for an author or book.',
 },
 {'name': 'bookshelf_create_rootfolder',
  'method': 'POST',
  'path': '/api/v1/rootfolder',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create rootfolder. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_list_rootfolder',
  'method': 'GET',
  'path': '/api/v1/rootfolder',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List rootfolder.',
 },
 {'name': 'bookshelf_update_rootfolder',
  'method': 'PUT',
  'path': '/api/v1/rootfolder/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update rootfolder. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_rootfolder',
  'method': 'DELETE',
  'path': '/api/v1/rootfolder/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete rootfolder. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_rootfolder',
  'method': 'GET',
  'path': '/api/v1/rootfolder/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single rootfolder by id.',
 },
 {'name': 'bookshelf_search',
  'method': 'GET',
  'path': '/api/v1/search',
  'pp': [],
  'qp': [
          {'name': 'term', 'wire': 'term', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Search for new books/authors on the metadata provider by term and return the matches to add.',
 },
 {'name': 'bookshelf_list_series',
  'method': 'GET',
  'path': '/api/v1/series',
  'pp': [],
  'qp': [
          {'name': 'author_id', 'wire': 'authorId', 'type': 'int', 'default': None},
         ],
  'bk': 'none',
  'doc': 'List series. Query params: authorId.',
 },
 {'name': 'bookshelf_get_system_status',
  'method': 'GET',
  'path': '/api/v1/system/status',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get system status: app name, version, OS, build, and runtime.',
 },
 {'name': 'bookshelf_get_system_routes',
  'method': 'GET',
  'path': '/api/v1/system/routes',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List system routes.',
 },
 {'name': 'bookshelf_get_system_routes_duplicate',
  'method': 'GET',
  'path': '/api/v1/system/routes/duplicate',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List system routes duplicate.',
 },
 {'name': 'bookshelf_shutdown',
  'method': 'POST',
  'path': '/api/v1/system/shutdown',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Shut down the Bookshelf service.',
 },
 {'name': 'bookshelf_restart',
  'method': 'POST',
  'path': '/api/v1/system/restart',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Restart the Bookshelf service.',
 },
 {'name': 'bookshelf_list_tag',
  'method': 'GET',
  'path': '/api/v1/tag',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List tag.',
 },
 {'name': 'bookshelf_create_tag',
  'method': 'POST',
  'path': '/api/v1/tag',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create tag. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_update_tag',
  'method': 'PUT',
  'path': '/api/v1/tag/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update tag. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_delete_tag',
  'method': 'DELETE',
  'path': '/api/v1/tag/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete tag. DESTRUCTIVE: this deletes data.',
 },
 {'name': 'bookshelf_get_tag',
  'method': 'GET',
  'path': '/api/v1/tag/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single tag by id.',
 },
 {'name': 'bookshelf_list_tag_detail',
  'method': 'GET',
  'path': '/api/v1/tag/detail',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List tag detail.',
 },
 {'name': 'bookshelf_get_tag_detail',
  'method': 'GET',
  'path': '/api/v1/tag/detail/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single tag detail by id.',
 },
 {'name': 'bookshelf_get_system_task',
  'method': 'GET',
  'path': '/api/v1/system/task',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List system task.',
 },
 {'name': 'bookshelf_get_system_task_by_id',
  'method': 'GET',
  'path': '/api/v1/system/task/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single system task by id.',
 },
 {'name': 'bookshelf_update_config_ui',
  'method': 'PUT',
  'path': '/api/v1/config/ui/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update config ui. WRITE: this modifies your Bookshelf instance.',
 },
 {'name': 'bookshelf_get_config_ui_by_id',
  'method': 'GET',
  'path': '/api/v1/config/ui/{id}',
  'pp': [
          {'name': 'id', 'wire': 'id', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Fetch a single config ui by id.',
 },
 {'name': 'bookshelf_get_config_ui',
  'method': 'GET',
  'path': '/api/v1/config/ui',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List config ui.',
 },
 {'name': 'bookshelf_list_update',
  'method': 'GET',
  'path': '/api/v1/update',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List update.',
 },
 {'name': 'bookshelf_list_log_file_update',
  'method': 'GET',
  'path': '/api/v1/log/file/update',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'List log file update.',
 },
]


def _tool_source(spec: dict[str, Any]) -> str:
    parts: list[str] = []
    for p in spec["pp"]:
        parts.append(f"{p['name']}: {p['type']}")
    for q in spec["qp"]:
        parts.append(f"{q['name']}: {q['type']} = {q['default']}")
    if spec["bk"] == "dict":
        parts.append("body: dict[str, Any] = {}")
    elif spec["bk"] == "list":
        parts.append("body: list[Any] = []")
    sig = ", ".join(parts)

    path_tmpl = spec["path"]
    for p in spec["pp"]:
        path_tmpl = path_tmpl.replace("{" + p["wire"] + "}", "{" + p["name"] + "}")
    if spec["pp"]:
        arg_call = ", ".join(f"{p['name']}=quote(str({p['name']}))" for p in spec["pp"])
        url_expr = f'f"{path_tmpl}".format({arg_call})'
    else:
        url_expr = repr(spec["path"])

    if spec["qp"]:
        params_expr = "_omit({" + ", ".join(f'"{q["wire"]}": {q["name"]}' for q in spec["qp"]) + "})"
    else:
        params_expr = "None"
    json_expr = "body" if spec["bk"] != "none" else "None"

    doc = spec["doc"].replace("\\", "\\\\").replace("\"\"\"", '\"\"\"')
    return (
        f"async def {spec['name']}({sig}) -> JSONVal:\n"
        f'    """{doc}"""\n'
        f"    return await _req({spec['method']!r}, {url_expr}, params={params_expr}, json_body={json_expr})\n"
    )


def _op_line(name: str, fn: Any) -> str:
    """One line of a group tool's description: signature + one-line doc."""
    sig = ", ".join(
        p.name if p.default is inspect.Parameter.empty else f"{p.name}={p.default!r}"
        for p in inspect.signature(fn).parameters.values()
    )
    return f"- {name}({sig}) — {' '.join((fn.__doc__ or '').split())}"


def _register_group(group: str, names: tuple[str, ...], ns: dict[str, Any], method_of: dict[str, str]) -> None:
    """Register one dispatching tool that fans out to every endpoint function
    named in `names`. The endpoint functions themselves are untouched -
    they're just looked up by name instead of each becoming its own tool."""
    fns = {n: ns[n] for n in names}

    async def dispatch(operation: str, arguments: JSONObj | None = None) -> JSONVal:
        fn = fns.get(operation)
        if fn is None:
            raise ToolError(f"Unknown operation {operation!r} for {group}. Valid: {', '.join(fns)}")
        return await fn(**(arguments or {}))

    dispatch.__annotations__["operation"] = Literal[names]
    ann = READONLY if {method_of[n] for n in names} == {"GET"} else None
    mcp.add_tool(
        Tool.from_function(
            dispatch,
            name=group,
            description=(
                f"{group.replace('_', ' ')} operations on Bookshelf. Pass `operation` and an "
                f"`arguments` dict matching that operation's parameters.\n\n"
                + "\n".join(_op_line(n, f) for n, f in fns.items())
            ),
            annotations=ann,
        )
    )


def register_tools() -> None:
    src = "\n".join(_tool_source(spec) for spec in _TOOL_REGISTRY)
    ns: dict[str, Any] = {}
    exec(src, globals(), ns)
    method_of = {spec["name"]: spec["method"] for spec in _TOOL_REGISTRY}
    for group, names in _GROUPS.items():
        _register_group(group, names, ns, method_of)


register_tools()


def main() -> None:
    global _client
    url = os.environ.get("BOOKSHELF_URL")
    if not url:
        print("BOOKSHELF_URL environment variable is required (e.g. http://bookshelf.example.com)", file=sys.stderr)
        raise SystemExit(1)
    _client = build_client(url, os.environ.get("BOOKSHELF_API_KEY"))
    mcp.run()


if __name__ == "__main__":
    main()
